# Lista de Exercícios Arrays NumPy

Exercício 1

In [ ]:
import numpy as np
arr1 = np.ones(8) # Criando um array de 8 elementos com valor 1
arr2 = np.random.randint(0, 9, 8) #Criando um array de 8 elementos com valores aleatórios entre 0 e 9
print(arr1)
print(arr2)

arr3 = np.add(arr1, arr2) #Somanado os valores de arr1 e arr2
print("------------------")

# Lógica para verificar se a soma dos elementos de arr3 é maior ou igual a 40
# Se for, o array é redimensionado para 4x2. Se não, o array é redimensionado para 2x4
if np.sum(arr3) >= 40:
    arr3 = np.reshape(arr3, (4, 2))
    print(arr3)
else:
    arr3 = np.reshape(arr3, (2, 4))
    print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1.]
[1 7 5 2 6 2 7 4]
------------------
[[2. 8.]
 [6. 3.]
 [7. 3.]
 [8. 5.]]


Exerccício 2

In [22]:
arr1 = np.arange(0, 51, 2)
arr2 = np.arange(100, 50, -2)
arr3 = np.concatenate((arr1, arr2))

print(arr1)
print(arr2)
print("-------------------------------------------------------------------------")
print(arr3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]
-------------------------------------------------------------------------
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50 100  98  96  94  92  90  88  86  84  82
  80  78  76  74  72  70  68  66  64  62  60  58  56  54  52]


Exercício 3

In [34]:
mtz = np.zeros((2, 2))
#adicionando um umero 1 em alguma posiçao aleatoria da matriz
mtz[np.random.randint(0, 2), np.random.randint(0, 2)] = 1
#criando um mini campo minado
print("Selecione uma posição da matriz: ")
if mtz[int(input("Digite a linha: "))][int(input("Digite a coluna: "))] == 1:
    print("Game over! :( Try again!")
else:
    print("Congralations! You beat the game! :)")

print("Confira onde estava o numero 1: \n", mtz)

Selecione uma posição da matriz: 
Congralations! You beat the game! :)
Confira onde estava o numero 1: 
 [[1. 0.]
 [0. 0.]]


Exercício 4

In [41]:
colunms = int(input("Digite o numero de colunas"))
lines = int(input("Digite o numero de linhas"))

mtz = np.random.randint(0, 9, (colunms, lines))

# Como o exercício pediu pra eu tirar o número de linhas e colunas por meio de funções aprendidas durante a aula, vou utilizar a função shape
print("Numero de colunas: ", mtz.shape[0])
print("Numero de linhas: ", mtz.shape[1])

aux = mtz.shape[0] * mtz.shape[1]

if(aux % 2 == 0):
    print("Pode se transformar em um array unidimensional par")
else:
    print("Pode se transformar em um array unidimensional impar")


Numero de colunas:  3
Numero de linhas:  3
Pode se transformar em um array unidimensional impar


Exercício 5

In [39]:
np.random.seed(10)
mtz = np.random.randint(1, 50, (4, 4))

sum_column = mtz.sum(axis=0)
sum_line = mtz.sum(axis=1)

print(mtz)
print(f"A média de cada uma das colunas é: {sum_column/4} e das linhas: {sum_line/4}")
print(f"O maior valor das médias das linhas é: {np.max(sum_line/4)} e o menor valor das médias das colunas é: {np.min(sum_column/4)}")
print("A quantidade de aparição de cada um dos números é: ", np.unique(mtz, return_counts=True))
print("Os números que apareceram 2 vezes são: ", np.unique(mtz, return_counts=True)[0][np.unique(mtz, return_counts=True)[1] == 2])	


[[10 37 16  1]
 [29 26 30 49]
 [30  9 10  1]
 [43 41 37 17]]
A média de cada uma das colunas é: [28.   28.25 23.25 17.  ] e das linhas: [16.  33.5 12.5 34.5]
O maior valor das médias das linhas é: 34.5 e o menor valor das médias das colunas é: 17.0
A quantidade de aparição de cada um dos números é:  (array([ 1,  9, 10, 16, 17, 26, 29, 30, 37, 41, 43, 49], dtype=int32), array([2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1]))
Os números que apareceram 2 vezes são:  [ 1 10 30 37]
