## Exercícios no final do arquivo 🚨

Iniciando com numpy

In [25]:
import numpy as np

#NunPy Array Unidimensional
arr = np.array([1, 2, 3, 4, 5])

#NubPy array Multidimensional
mtz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  

print(arr)
print(mtz) 

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


CRIANDO NUMPY ARRAYS COM MAIS FACILIDADE

In [3]:
#Estruturando rapidamente uma matriz de 1's
mtz = np.ones((5, 5))
print(mtz)

#arrange
mtz = np.arange(10)
print(mtz)
mtz = np.arange(10, 30, 2)
print(mtz)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24 26 28]


OPERAÇÕES COM NUMPY ARRAYS

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1.min(), arr1.max())
print(arr1.argmin(), arr1.argmax()) #Posição do menor e maior

print(arr1.mean(), arr1.sum())

#OPERAÇÕES ENTRE DOIS OU MAIS ARRAYS
arr3 = arr1 + arr2	
print(arr3)

#CONCATENANDO NUMPY ARRAYS
arr3 = np.concatenate((arr1, arr2))
print(arr3)

1 4
0 3
2.5 10
[ 6  8 10 12]
[1 2 3 4 5 6 7 8]


RESHAPE DE NUMPY ARRAYS

In [ ]:
mtz = np.arange(9).reshape(3,3)
print(mtz)

# print(mtz.size)
# print(mtz.shape)
# print(mtz.ndim)

# OPERAÇÕES NAS LINHAS E COLUNAS DA MATRIZ
print(mtz.sum(axis=0)) #Soma das colunas
print(mtz.sum(axis=1)) #Soma das linhas


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
2
[ 9 12 15]
[ 3 12 21]


BROADCASTING   (Multiplicar um escalar por um vetor)

In [8]:
print(mtz/2)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


ELEMENTOS ALEATÓRIOS E ÚNICOS

In [ ]:
# GERANDO NUMEROS ALEATORIOS
np.random.seed(10) #trabalhando com semente de dados (sempre será igual)
arr = np.random.randint(20, 30, 10)
arr1 = np.random.randint(10, 20, [5,5]) #Matriz 5x5 aleatoria
print(arr)
print(arr1)

#Extraindo valores unicos de um array com unique
print(np.unique(arr, return_counts=True)) #Retorna os valores unicos e a quantidade de vezes que eles aparecem

[29 24 20 21 29 20 21 28 29 20]
[[18 16 14 13 10]
 [14 16 18 11 18]
 [14 11 13 16 15]
 [13 19 16 19 11]
 [19 14 12 16 17]]
(array([20, 21, 24, 28, 29], dtype=int32), array([3, 2, 1, 1, 3]))


SLICING DE NUMPY ARRAYS (BIDIMENSIONAIS)

In [4]:
mtz = np.arange(1, 10, 1).reshape(3,3)
print(mtz)

# Slicing em uma unica linha
print(mtz[2])

# Slicing de multiplas linhas
print(mtz[1:])

# Slicing de uma coluna
print(mtz[:, 1])

# Slicing de multiplas colunas
print(mtz[:, 1:])   

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]


CONDICIONAL

In [7]:
print(mtz > 5)
print(mtz[mtz > 5]) 

print(mtz % 2 == 0)
print(mtz[mtz % 2 == 0])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


TRABALHANDO COM PADROES TEXTUAIS NO NUMPY

In [ ]:
arr = np.array(['Goku', 'Vegeta', 'Gohan', 'Bulma', 'Goten'])
print(arr[np.char.find(arr, 'Go') >= 0])

print(arr[np.char.find(arr, 'a') >= 0])

['Goku' 'Gohan' 'Goten']
['Vegeta' 'Gohan' 'Bulma']


IMPORTANDO ARQUIVOS EXTERNOS NO NUMPY

In [ ]:
import numpy as np

# Carregar o dataset, removendo espaços extras do delimitador
dataset = np.loadtxt('space.csv', delimiter=';', dtype=str, encoding='utf-8')

# Corrigir possíveis espaços nos nomes das colunas
dataset[0, :] = np.char.strip(dataset[0, :])  # Remove espaços do cabeçalho

# Exibir as colunas para verificar a estrutura
print("Colunas:", dataset[0, :])

# Exibir a primeira linha para verificar os dados
print("Primeira linha:", dataset[1, :])

# Identificar índice correto da coluna "Cost"
cost_index = np.where(dataset[0, :] == 'Cost')[0][0]  # Identifica a coluna correta

# Remover o cabeçalho do dataset para evitar problemas ao converter valores
data = dataset[1:, :]

# 1. Porcentagem de missões bem-sucedidas
success_count = np.sum(data[:, 7] == 'Success')  # Contar "Success" na coluna 7
total_missions = data.shape[0]  # Total de missões
success_percentage = (success_count / total_missions) * 100
print(f'Porcentagem de missões bem-sucedidas: {success_percentage:.2f}%')

# 2. Média de gastos das missões com valores disponíveis (> 0)
costs = data[:, cost_index]  # Selecionar a coluna correta de custos
costs = np.char.strip(costs)  # Remover espaços em branco ao redor
costs = np.char.replace(costs, ',', '')  # Remover vírgulas caso existam
costs = np.where(costs == '', '0', costs)  # Substituir strings vazias por '0'
costs = costs.astype(float)  # Converter para float
valid_costs = costs[costs > 0]  # Filtrar valores positivos
mean_cost = np.mean(valid_costs) if len(valid_costs) > 0 else 0
print(f'Média dos custos das missões: {mean_cost:.2f}')

# 3. Quantidade de missões realizadas pelos Estados Unidos
usa_missions = np.sum(data[:, 2] == 'USA')
print(f'Quantidade de missões realizadas pelos EUA: {usa_missions}')

# 4. Missão mais cara realizada pela SpaceX
spacex_index = np.where(dataset[0, :] == 'Company Name')[0][0]  # Identificar a coluna correta
spacex_costs = costs[data[:, spacex_index] == 'SpaceX']  # Filtrar custos da SpaceX
most_expensive = np.max(spacex_costs) if len(spacex_costs) > 0 else 0
print(f'Missão mais cara realizada pela SpaceX: {most_expensive:.2f}')


# 5. Nome das empresas e quantidade de missões realizadas
unique_companies, mission_counts = np.unique(dataset[:, 1], return_counts=True)
print('Quantidade de missões por empresa:')
for company, count in zip(unique_companies, mission_counts):
    print(f'{company}: {count}')


Colunas: ['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 'Cost' 'Status Mission']
Primeira linha: ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA'
 'Fri Aug 07 2020 05:12 UTC'
 'Falcon 9 Block 5 | Starlink V1 L9 & BlackSky' 'StatusActive' '50.0 '
 'Success']
Porcentagem de missões bem-sucedidas: 89.71%
Média dos custos das missões: 153.79
Quantidade de missões realizadas pelos EUA: 0
Missão mais cara realizada pela SpaceX: 90.00
Quantidade de missões por empresa:
AEB: 3
AMBA: 8
ASI: 9
Arianespace: 279
Arm??e de l'Air: 4
Blue Origin: 12
Boeing: 136
CASC: 251
CASIC: 5
CECLES: 4
CNES: 8
Company Name: 1
Douglas: 1
EER: 1
ESA: 13
Eurockot: 13
ExPace: 10
Exos: 4
General Dynamics: 251
IAI: 11
ILS: 46
IRGC: 1
ISA: 13
ISAS: 30
ISRO: 76
JAXA: 7
KARI: 3
KCST: 5
Khrunichev: 1
Kosmotras: 22
Land Launch: 7
Landspace: 1
Lockheed: 79
MHI: 84
MITT: 7
Martin Marietta: 114
NASA: 203
Northrop: 83
OKB-586: 2
OneSpace: 1
RAE: 2
RVSN USSR: 1777
Rocket Lab: 13
Roscosmos: 55
SRC